---
arch: amd64
os: linux
dist: focal
language: cpp
compiler: gcc
env:
  - VCPKG_TRIPLET=x64-linux

git:
  strategy: clone
  depth: false

addons:
  sonarcloud:
    organization: "ots-1"
    token:
      secure: 5e2b89be5a71d5080b74a91e498c75e68c21f853
  apt:
    update: true
    packages:
      - ccache
      - build-essential
      - cmake
      - libluajit-5.1-dev
      - tar
      - curl
      - zip
      - unzip

install:
  - cd /home/travis/build/Gha
  - git clone https://github.com/microsoft/vcpkg
  - ./vcpkg/bootstrap-vcpkg.sh
  - ./vcpkg/vcpkg integrate install

script:
  - cd /home/travis/build/Gha/otservbr-global
  - export CXXFLAGS="$CXXFLAGS -DBOOST_ASIO_DISABLE_NOEXCEPT=1 "
  - /home/travis/build/Gha/vcpkg/vcpkg --feature-flags=binarycaching,manifests,versions install
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=/home/travis/build/Gha/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cd ..
  - NUMBER_OF_PROCESSORS=$(nproc --all)
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
  - sonar-scanner -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=${TRAVIS_HOME}/.cfamily -Dsonar.cfamily.threads=${NUMBER_OF_PROCESSORS} || true

  # - sonar-scanner -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=${TRAVIS_HOME}/.cfamily -Dsonar.cfamily.threads=${NUMBER_OF_PROCESSORS} || true
  # - curl --upload-file /home/travis/build/Gha/otservbr-global/sonar-cfamily-reproducer.zip https://transfer.sh/sonar-cfamily-reproducer.zip

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/.ccache
    - $HOME/.cfamily
